name: fb_auth_riverpod
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^11.1.4
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  url_strategy: ^0.2.0
  validators: ^3.0.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  riverpod_lint:
  custom_lint:
  build_runner:
  freezed:
  riverpod_generator:

flutter:
  uses-material-design: true
